# Generated by Django 5.1 on 2024-08-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('comment_added', 'Comment Added'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='rest_api.comment')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='rest_api.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='rest_api.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='rest_api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
